### ISSUE TITLE
The app cannot be installed because its integrity could not be verified on iOS 14.4

### ISSUE THREAD

**Issue by tomasbrincil** [thepoweroftwo/meshtastic-ios#2]
I connected the iPhone X to my mac, drag the meshastic_0.86.ipa drop in the Finder to the phone but whe I try open there is error. Am I doing something wrong?

https://imgur.com/a/Q04xjdu

**Comment by thepoweroftwo** [comment]
You're not doing something wrong, these prebuilt .ipa can only be installed with a jailbreak because they are not signed.

You have 2 options:
- Download the source and compile it yourself with XCode
- Write me your email address and full name (should match the one you use in your apple account) to kontakt@tobiashuttinger.de, so I can add you to the app testflight
